### ISSUE TITLE
Expenses are not visible when users are hovering over them

### ISSUE THREAD

**Issue by valentin-aleksandrov** [TheaAleksovDev/budgetCalculator#4]
![image](https://github.com/user-attachments/assets/c449a55a-72c0-4b15-8cf0-ce2540287be9)

Notice what happens when I hover over the above item:

![image](https://github.com/user-attachments/assets/191759d2-e050-46f7-9733-ab2831d674b8)

I discovered this while reviewing:
- https://github.com/TheaAleksovDev/budgetCalculator/pull/1

**Comment by TheaAleksovDev** [comment]
![Untitled](https://github.com/user-attachments/assets/ef427a17-51dd-4501-8e34-2a5c5ae01cf3)
Looks like it works just fine when I try it. Can you provide more details about this bug?

**Comment by TheaAleksovDev** [comment]
Got it. The hover effect was not working only on boundary values that weren’t included. It should work as expected now.
